timezone: 'EST'
wartimes:
    wartime-1:
        wartime-start: '18:00'
        wartime-end: '19:00'
        wartime-active-text: "&c&lIt's now Wartime!"
        bar-color: "RED"
        warning-text: "&cWartime starts in %mins% minutes!"
        warning-bar-color: "RED"
        warnings:
        - 5
        - 10
        - 15