name: AelusenWartime
main: me.pseudo.Aelusen.AelusenWartime
author: Pseudo
version: 0.01
commands:
    listwartimes:
        description: List wartimes!
        usage: /<command>
    wartimereload:
        description: Reloads Wartimes!
        usage: /<command>